; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25547.0 

	TITLE	F:\UQAC\Ia_pour_jv\TP1\VS2010\Buckland_Chapter7 to 10_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
